name: CI Pipeline

# When to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  # Test job
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install backend dependencies
      run: |
        cd intelligent-ecommerce/backend
        npm ci
    
    - name: Install frontend dependencies
      run: |
        cd intelligent-ecommerce/frontend
        npm ci
    
    - name: Run backend tests
      run: |
        cd intelligent-ecommerce/backend
        npm test
    
    - name: Run frontend tests
      run: |
        cd intelligent-ecommerce/frontend
        npm test -- --coverage --watchAll=false --passWithNoTests
    
    - name: Build backend
      run: |
        cd intelligent-ecommerce/backend
        npm run build
    
    - name: Build frontend
      run: |
        cd intelligent-ecommerce/frontend
        npm run build

  # Build Docker images
  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./intelligent-ecommerce/backend
        push: true
        tags: ghcr.io/${{ github.repository }}-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./intelligent-ecommerce/frontend
        push: true
        tags: ghcr.io/${{ github.repository }}-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Deploy
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [test, build-docker]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        echo "Backend image: ghcr.io/${{ github.repository }}-backend:latest"
        echo "Frontend image: ghcr.io/${{ github.repository }}-frontend:latest"